favicon: /favicon.ico


# Nav Menus
menu:
    首页: /
    基础概念: /categories/basic/
    高级主题: /categories/advanced/
    最佳实践: /categories/practice/
    书籍推荐: /book
    开源项目: /categories/projects/

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/AngryPowman']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['wecatch', 'wecatch', 'http://wecatch.me']


# About
about_info:
    name: "wecatch"
    bio: "wecatch 官方出品 Go 教程"
    avatar: "https://avatars0.githubusercontent.com/u/7918984?s=200&v=4"

# Comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# Analytics
google_analytics: UA-79591400-1
tencent_analytics: 
 
# Copyright Infomation
startyear: 2017
